"""Bounded union of the two existing optional-event hypothesis beams.

Enabled only when both explicit source policies are on. Each arm contributes
exactly the alternatives its own single-arm module already builds, in a fixed
source order, under the one shared search budget. No per-point policy is chosen
and no saved output is spliced.

Under the legacy v1 bounce policy only final-gap contact pairs compose. The
explicit ``classifier_v2`` and conservative ``classifier_interior`` bounce modes
also compose interior pairs in a bounded joint family
from those same two witnesses: the first ``MAX_JOINT`` source-ordered
contact-by-bounce pairs, refused rather than repaired when the two arms would
interfere. ``joint`` is a selection family, not a third source witness, so the
binding loaders below keep iterating the two real witnesses.

The arms deliberately keep their own emission bindings: the contact witness
declares the stage's original event file, while the bounce witness declares the
selected ``automatic_events.json`` that preparation wrote. Those documents are
never concatenated. This module re-verifies each declared binding, checks that
both witnesses were built on the same accepted event stream, and refuses a
contact candidate whose source row is outside the shared selected emissions.

The explicit ``conditional_grounds`` composition policy, default off, adds one
more bounded joint family from those same two witnesses. For each contact
alternative the contact arm already offers, the bounce witness's own held-ground
qualification rule is re-run on its own original emissions with exactly one
argument changed: the accepted stream plus that alternative's added contacts.
Only grounds owned by a gap the added contact itself created are offered, so the
original bounce inventory never gains a row and every existing single-arm and
composed branch stays byte-identical. The result is bound to the original event
stream and the exact contact hypothesis and is regenerated by every reader.
"""

from __future__ import annotations

from copy import deepcopy
import hashlib
import json

from cv.pipeline import provenance

SCHEMA = "s6_optional_event_union_v1"
# The two independent source witnesses. Every binding loader iterates these.
FAMILIES = ("contact", "bounce")
SUPPLIED = "supplied"
# `joint` is a selection family composed from those same two witnesses. There is
# no third witness and no third binding: it is named separately so that nothing
# which loads or verifies a witness can be handed it by mistake.
JOINT = "joint"
MAX_JOINT = 2
SELECTION_FAMILIES = (*FAMILIES, JOINT)
POLICIES = {
    "contact": "source_witness_optional_contact_v1",
    "bounce": "source_witness_optional_bounce_v1",
    JOINT: "source_witness_optional_joint_v2",
}
PREFIXES = {
    "contact": "optional_contacts_",
    "bounce": "optional_bounces_",
    JOINT: "optional_joint_",
}
RECEIPT_FILES = {
    "contact": "optional_contact_search.json",
    "bounce": "optional_bounce_search.json",
    JOINT: "optional_joint_search.json",
}
# Conditional ground composition: a selection policy over the same two witnesses.
CONDITIONAL = "conditional_grounds"
CONDITIONAL_POLICIES = ("off", "on")
CONDITIONAL_SCHEMA = "s6_conditional_ground_inventory_v1"
CONDITIONAL_PREFIX = "conditional_grounds_"
# Conditional pairs share the ORIGINAL joint cap: they may only fill the joint
# slots the existing original-pair composition left empty. Timing pairs are the
# existing separately capped subfamily and are neither counted nor displaced.
MAX_CONDITIONAL = MAX_JOINT
GAP_NOT_CREATED = "gap_not_created_by_the_added_contact"
JOINT_CAP_REACHED = "fixed_joint_pair_limit_reached"


def conditional_policy(value: str | None) -> str:
    value = "off" if value is None else value
    if value not in CONDITIONAL_POLICIES:
        raise ValueError("explicit conditional ground composition policy required")
    return value


def _digest(value) -> str:
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False).encode()
    ).hexdigest()


def _schemas() -> dict[str, tuple[str, ...]]:
    from cv.pipeline import s6_optional_bounce_scope, s6_optional_contacts

    return {
        "contact": s6_optional_contacts.SCHEMAS,
        "bounce": (s6_optional_bounce_scope.WITNESS_SCHEMA,),
    }


def final_contact_scope(documents: dict[str, dict]) -> bool:
    """Whether the contact witness declares the additive final-gap scope."""
    from cv.pipeline import s6_optional_contacts

    return s6_optional_contacts.declared_final_scope(documents["contact"])


def bound_events(family: str, document: dict) -> list[dict] | None:
    """The accepted event stream each witness family declares it was built on."""
    return document.get("source_attempt_events" if family == "contact" else "original_events")


def family_of(name: str | None) -> str | None:
    if name == SUPPLIED:
        return SUPPLIED
    # Independent source cues currently construct contact-only alternatives.
    # This routes them to the same reader, which still recomputes the exact
    # topology/events from the bound witness; a name alone admits nothing.
    if isinstance(name, str) and name.startswith("independent_proposal_"):
        return "contact"
    for family, prefix in PREFIXES.items():
        if isinstance(name, str) and name.startswith(prefix):
            return family
    return None


def composes_v2(documents: dict[str, dict]) -> bool:
    """Whether the existing bounce witness also changes candidate admission."""
    from cv.pipeline import s6_optional_bounces

    return documents["bounce"].get("mode") == s6_optional_bounces.MODE_V2


def composes_interior(documents: dict[str, dict]) -> bool:
    """Interior composition is explicit and independent of v2 admission."""
    from cv.pipeline import s6_optional_bounces

    return documents["bounce"].get("mode") in s6_optional_bounces.INTERIOR_MODES


def composes(documents: dict[str, dict]) -> bool:
    """Composition is additionally available to the declared final-contact scope.

    Under the v1 bounce witness only pairs carrying a final-gap contact compose,
    so interior-only combinations still require an explicit interior bounce mode.
    Turning the final-contact scope on does not enable v2 bounce admission.
    """
    return composes_interior(documents) or final_contact_scope(documents)


def _interval(event: dict) -> list[float]:
    return event.get("frame_interval", [event["frame"], event["frame"]])


def _final_added(hypothesis: dict) -> list[dict]:
    return [row for row in hypothesis["added"] if row.get("optional_gap_kind") == "final"]


def _overlaps(first, second) -> bool:
    return max(first[0], second[0]) <= min(second[1], first[1])


def _not_composable(
    contact: dict, bounce: dict, documents: dict[str, dict], attempt: dict
) -> str | None:
    """Refuse a pair whose two arms would interfere, rather than repairing it.

    Recomputing gap ownership under the added contacts would let those pairs
    compose; that is deliberately a later decision, not part of this mechanism.
    """
    inventory = documents["bounce"].get("inventory", {})
    gaps = inventory.get("gaps", [])
    owner = {row["id"]: row["gap_index"] for row in inventory.get("candidates", [])}
    # Every original bounce candidate is validated against its own source inventory
    # first. No ordering permission below may skip this: an unbound candidate or a
    # missing owner gap is a different source population, not an extra hypothesis.
    for candidate in bounce["candidate_ids"]:
        if candidate not in owner:
            return "bounce_candidate_outside_its_own_source_inventory"
        index = owner[candidate]
        if not isinstance(index, int) or not 0 <= index < len(gaps) or len(gaps[index]) != 2:
            return "bounce_candidate_owner_gap_missing_from_its_source_inventory"
    # A ground after an added contact is an ordinary terminal flight for a supplied
    # ending and for an observation horizon, but a declared terminal net tail admits
    # exactly zero grounds on its final flight, so that one scope cannot express it.
    # Refuse only that scope; nothing here forbids an after-contact ground generally.
    net_tail = attempt.get("terminal_net_tail") is not None
    for added in contact["added"]:
        interval = _interval(added)
        if any(_overlaps(interval, _interval(row)) for row in bounce["added"]):
            return "added_contact_and_bounce_intervals_overlap"
        # A final-gap contact may split the gap that owns a bounce candidate when the
        # added intervals are separated and uniquely ordered: each added bounce lies
        # wholly before or wholly after the contact, so the sub-gap it belongs to is
        # unambiguous and ordinary preparation assigns the observations. Interior
        # contacts keep the existing refusal exactly.
        if added.get("optional_gap_kind") == "final" and bounce["added"]:
            if not all(
                _interval(row)[1] < interval[0] or _interval(row)[0] > interval[1]
                for row in bounce["added"]
            ):
                return "added_final_contact_and_bounce_intervals_are_not_uniquely_ordered"
            if net_tail and any(_interval(row)[0] > interval[1] for row in bounce["added"]):
                return "declared_terminal_net_tail_admits_no_ground_after_an_added_contact"
            continue
        for candidate in bounce["candidate_ids"]:
            left, right = gaps[owner[candidate]]
            if left < interval[1] and interval[0] < right:
                return "added_contact_splits_the_gap_that_owns_a_bounce_candidate"
    return None


def conditional_inventory(documents: dict[str, dict], contact: dict) -> dict:
    """Re-qualify held source grounds under one contact hypothesis' partition.

    The SAME frozen rule (``s6_optional_bounces.source_candidates``) runs on the
    bounce witness's own original emissions, clip key, native window, ending or
    horizon and candidate mode; only the event list changes, to the contact
    hypothesis' events. No probability, interval or type is touched and no
    event is invented. A ground whose owner gap is not bounded by an added
    contact was equally expressible before the split and stays the original
    arm's business: it is held here so this family never re-offers it.
    """
    from cv.pipeline import s6_optional_bounce_scope, s6_optional_bounces

    bounce = documents["bounce"]
    inventory = bounce["inventory"]
    # The witness builder calls the rule without aligned ground evidence in every
    # mode it supports, so the same call here is its exact rule. A witness built
    # any other way is refused rather than re-qualified under a different rule.
    if bounce.get("mode") not in s6_optional_bounce_scope.MODES:
        raise ValueError("conditional grounds require a supported optional bounce witness mode")
    if bounce.get("ground_evidence_files_read") is not False:
        raise ValueError(
            "conditional grounds require a witness built without aligned ground evidence"
        )
    added = [float(e["frame"]) for e in contact["added"] if e["event_type"] == "contact"]
    if not added:
        raise ValueError("conditional grounds require a contact hypothesis with added contacts")
    document = s6_optional_bounces.source_candidates(
        contact["events"],
        bounce["original_emissions"],
        inventory["clip"],
        tuple(bounce["native_window"]),
        end_frame=inventory["end_frame"],
        mode=bounce["mode"],
    )
    retained = []
    for row in document["candidates"]:
        left, right = document["gaps"][row["gap_index"]]
        if float(left) in added or float(right) in added:
            retained.append(row)
        else:
            document["held_candidates"].append(
                {"source_emission_index": row["source_emission_index"], "reason": GAP_NOT_CREATED}
            )
    document["candidates"] = retained
    document["conditional_grounds"] = {
        "schema": CONDITIONAL_SCHEMA,
        "contact_hypothesis": contact["name"],
        "contact_candidate_ids": list(contact["candidate_ids"]),
        "original_events_sha256": _digest(bounce["original_events"]),
        "partition_sha256": _digest(contact["events"]),
        "added_contact_frames": added,
        "bounce_mode": bounce["mode"],
        "qualification": "s6_optional_bounces.source_candidates on the contact hypothesis partition",
        "original_inventory_changed": False,
        "ground_evidence_files_read": False,
        "candidate_ids": [row["id"] for row in retained],
        "gaps": [[float(a), float(b)] for a, b in document["gaps"]],
    }
    return document


def _conditional_refusal(contact: dict, bounce: dict, documents: dict[str, dict], attempt: dict):
    """The composed pair's own interference checks, on the conditional inventory.

    Ownership was computed on the partition, so the split refusal is replaced by
    that binding; overlap, the declared terminal net tail and the bounce arm's
    own unknown-ending scope qualification are kept exactly.
    """
    from cv.pipeline import s6_optional_bounce_scope

    witness = documents["bounce"]
    last_contact = max(float(e["frame"]) for e in attempt["events"] if e["event_type"] == "contact")
    for added in contact["added"]:
        interval = _interval(added)
        if any(_overlaps(interval, _interval(row)) for row in bounce["added"]):
            return "added_contact_and_bounce_intervals_overlap"
    if attempt.get("terminal_net_tail") is not None and any(
        _interval(row)[0] > last_contact for row in bounce["added"]
    ):
        return "declared_terminal_net_tail_admits_no_ground_after_the_last_contact"
    if witness.get("physical_ending") is None:
        events = sorted(
            [*attempt["events"], *contact["added"], *bounce["added"]], key=lambda e: e["frame"]
        )
        _, hold = s6_optional_bounce_scope._qualify(
            events,
            witness["original_observations"],
            tuple(witness["native_window"]),
            witness["segmentation_source"],
            witness["allow_terminal_net"],
            witness.get("allow_observed_horizon", False),
        )
        if hold is not None:
            return f"unknown_ending_scope_held: {hold}"
    return None


def conditional_pairs(
    documents: dict[str, dict],
    attempt: dict,
    rows: dict[str, list[dict]],
    existing: list[dict],
    limit: int,
) -> tuple[list[dict], list[dict]]:
    """The first ``limit`` source-ordered conditional pairs, composed or refused.

    ``limit`` is the original joint capacity the existing composition left
    empty, so the joint family never fits more than MAX_JOINT original-pair
    branches in total. Contact alternatives keep the arm's own order; timing
    alternatives and final-scope additions are left to their existing
    compositions. Each pair's bounce alternatives come from the unchanged
    bounded bounce beam rule run on the conditional inventory, so at most one
    ground per resulting flight.
    """
    from cv.pipeline import s6_optional_bounces

    limit = max(0, min(int(limit), MAX_CONDITIONAL))
    ordered = []
    receipts: list[dict] = []
    for contact in rows["contact"]:
        if contact.get("contact_timing_alternative") or _final_added(contact):
            continue
        inventory = conditional_inventory(documents, contact)
        binding = inventory["conditional_grounds"]
        beam = s6_optional_bounces.hypotheses(
            inventory, contact["events"], documents["bounce"]["mode"]
        )
        if not beam:
            receipts.append(
                {
                    "contact_hypothesis": contact["name"],
                    "status": "no_conditional_ground",
                    "conditional_grounds": binding,
                }
            )
            continue
        for index, hypothesis in enumerate(beam, 1):
            ordered.append((contact, hypothesis, index, binding))
    alternatives: list[dict] = []
    for contact, hypothesis, index, binding in ordered[:limit]:
        pair = {
            "contact_hypothesis": contact["name"],
            "bounce_hypothesis": f"{CONDITIONAL_PREFIX}{index}",
            CONDITIONAL: {**binding, "ground_candidate_ids": list(hypothesis["candidate_ids"])},
        }
        reason = _conditional_refusal(contact, hypothesis, documents, attempt)
        if reason is None and any(
            row["events"] == hypothesis["events"] for row in [*existing, *alternatives]
        ):
            reason = "duplicate_of_an_existing_composed_hypothesis"
        if reason is not None:
            receipts.append({**pair, "status": "not_composable", "reason": reason})
            continue
        added = [*contact["added"], *hypothesis["added"]]
        alternatives.append(
            {
                "name": f"{PREFIXES[JOINT]}{len(existing) + len(alternatives) + 1}",
                "events": sorted([*attempt["events"], *added], key=lambda e: e["frame"]),
                "added": added,
                "candidate_ids": [*contact["candidate_ids"], *hypothesis["candidate_ids"]],
                "occurrence_log_odds": contact["occurrence_log_odds"]
                + hypothesis["occurrence_log_odds"],
                "added_parameter_count": 6 * len(contact["added"]),
                "added_contact_count": len(contact["added"]),
                "added_bounce_count": len(hypothesis["added"]),
                "source_family": JOINT,
                "joint_composition": deepcopy(pair),
            }
        )
        receipts.append({**deepcopy(pair), "status": "composed", "name": alternatives[-1]["name"]})
    for contact, hypothesis, index, binding in ordered[limit:]:
        receipts.append(
            {
                "contact_hypothesis": contact["name"],
                "bounce_hypothesis": f"{CONDITIONAL_PREFIX}{index}",
                "status": "not_composable",
                "reason": JOINT_CAP_REACHED,
            }
        )
    return alternatives, receipts


def composed(
    documents: dict[str, dict], attempt: dict, rows: dict[str, list[dict]]
) -> tuple[list[dict], list[dict]]:
    """The first MAX_JOINT source-ordered pairs, composed or explicitly refused.

    Fixed source order, no reference and no per-point choice: the arms' own
    orderings are taken as given and the product is truncated, never ranked.
    """
    import itertools

    # Interior-only v2 composition keeps its existing truncated source product.
    # A final-contact beam instead takes a deterministic round-robin so every
    # final contact candidate meets a bounce alternative before any contact
    # takes a second one. Neither order re-ranks an arm's own alternatives.
    if pair_order(rows) == FINAL_PAIR_ORDER:
        ordered = [
            (contact, bounce)
            for index in range(max(len(rows["bounce"]), 1))
            for contact in rows["contact"]
            for bounce in rows["bounce"][index : index + 1]
        ]
    else:
        ordered = list(itertools.product(rows["contact"], rows["bounce"]))
    timing_pairs = [(c, b) for c, b in ordered if c.get("contact_timing_alternative")]
    original_pairs = [(c, b) for c, b in ordered if not c.get("contact_timing_alternative")]
    pairs = original_pairs[:MAX_JOINT] + timing_pairs[:MAX_JOINT]
    alternatives: list[dict] = []
    receipts: list[dict] = []
    only_final = not composes_interior(documents)
    for contact, bounce in pairs:
        pair = {"contact_hypothesis": contact["name"], "bounce_hypothesis": bounce["name"]}
        if only_final and not _final_added(contact):
            receipts.append(
                {
                    **pair,
                    "status": "not_composable",
                    "reason": "interior_only_composition_requires_the_v2_bounce_witness",
                }
            )
            continue
        reason = _not_composable(contact, bounce, documents, attempt)
        if reason is not None:
            receipts.append({**pair, "status": "not_composable", "reason": reason})
            continue
        added = [*contact["added"], *bounce["added"]]
        alternatives.append(
            {
                "name": f"{PREFIXES[JOINT]}{len(alternatives) + 1}",
                "events": sorted([*attempt["events"], *added], key=lambda e: e["frame"]),
                "added": added,
                "candidate_ids": [*contact["candidate_ids"], *bounce["candidate_ids"]],
                "occurrence_log_odds": contact["occurrence_log_odds"]
                + bounce["occurrence_log_odds"],
                # Bounces add no continuous dimensions, as the bounce arm already
                # declares; each added contact carries the arm's implicit six.
                "added_parameter_count": 6 * len(contact["added"]),
                "added_contact_count": len(contact["added"]),
                "added_bounce_count": len(bounce["added"]),
                "source_family": JOINT,
                "joint_composition": pair,
            }
        )
        receipts.append({**pair, "status": "composed", "name": alternatives[-1]["name"]})
    return alternatives, receipts


FINAL_PAIR_ORDER = "round_robin_over_final_contact_alternatives_v1"
INTERIOR_PAIR_ORDER = "truncated_source_ordered_product_v1"


def pair_order(rows: dict[str, list[dict]]) -> str:
    """The disclosed pair ordering actually used for this contact beam."""
    return (
        FINAL_PAIR_ORDER
        if any(_final_added(row) for row in rows["contact"])
        else INTERIOR_PAIR_ORDER
    )


def check_source_binding(
    documents: dict[str, dict], attempt: dict, conditional_grounds: str = "off"
) -> dict:
    """Refuse a joint run whose two witnesses do not share one source binding."""
    from cv.pipeline.s6_labeled_stage import resolve

    conditional = conditional_policy(conditional_grounds) == "on"
    if set(documents) != set(FAMILIES):
        raise ValueError("joint optional beams require one contact and one bounce witness")
    from cv.pipeline import s6_terminal_net_membership as membership

    # Contact qualification retains the original accepted stream. The absent
    # bounce witness is deterministically requalified from its frozen original
    # file under the authorized effective stream; verify that derivation too.
    bound = membership.source_events(attempt)
    absent = membership.membership_of(attempt) == membership.ABSENT
    if absent:
        from cv.pipeline import s6_optional_bounce_scope

        if documents["bounce"] != s6_optional_bounce_scope.load_witness(attempt):
            raise ValueError("joint optional bounce witness differs from its membership derivation")
    schemas = _schemas()
    records = {}
    for family in FAMILIES:
        document = documents[family]
        if document.get("schema") not in schemas[family]:
            raise ValueError(f"joint optional {family} witness has the wrong source schema")
        expected = attempt["events"] if absent and family == "bounce" else bound
        if bound_events(family, document) != expected:
            raise ValueError(f"joint optional {family} witness does not bind the accepted events")
        record = document.get("source_events")
        if not isinstance(record, dict) or not isinstance(record.get("sha256"), str):
            raise ValueError(f"joint optional {family} witness needs a declared source binding")
        if provenance.file_sha256(resolve(record)) != record["sha256"]:
            raise ValueError(f"joint optional {family} source events changed")
        records[family] = record
    # The contact arm reads the whole stage event file and keys on the joined
    # clip alias; the bounce arm reads the selected rows preparation wrote. A
    # contact candidate outside that shared selection is a different source
    # population, not an additional hypothesis: refuse instead of merging.
    shared = documents["bounce"].get("original_emissions", [])
    for candidate in documents["contact"].get("candidates", []):
        if candidate.get("source_emission") not in shared:
            raise ValueError(
                "joint optional contact candidate is outside the shared selected source emissions"
            )
    return {
        "schema": SCHEMA,
        "families": list(FAMILIES),
        "source_events": records,
        "shared_selected_emissions": len(shared),
        "documents_concatenated": False,
        # Truthful per mode: v1 only concatenates the two beams, v2 additionally
        # composes bounded joint hypotheses out of the same two witnesses.
        "cross_composed_events": composes(documents) or conditional,
        **(
            {
                CONDITIONAL: {
                    "policy": "on",
                    "schema": CONDITIONAL_SCHEMA,
                    "pair_limit": MAX_CONDITIONAL,
                    "shares_original_joint_cap": True,
                    "bounce_witness_mode": documents["bounce"].get("mode"),
                    "original_inventory_changed": False,
                    "reference_or_gate_used": False,
                }
            }
            if conditional
            else {}
        ),
        **(
            {
                "joint_selection_family": JOINT,
                "joint_pair_limit": MAX_JOINT
                * (
                    2
                    if documents["contact"].get("contact_timing", {}).get("policy") == "pmf_peaks"
                    else 1
                ),
                **(
                    {
                        "original_joint_pair_limit": MAX_JOINT,
                        "additional_timing_pair_limit": MAX_JOINT,
                    }
                    if documents["contact"].get("contact_timing", {}).get("policy") == "pmf_peaks"
                    else {}
                ),
                "joint_pair_orders": [INTERIOR_PAIR_ORDER, FINAL_PAIR_ORDER],
            }
            if composes(documents) or conditional
            else {}
        ),
        **(
            {"final_contact_scope": documents["contact"]["scope"]}
            if final_contact_scope(documents)
            else {}
        ),
    }


def hypotheses(
    documents: dict[str, dict], attempt: dict, conditional_grounds: str = "off"
) -> tuple[list[dict], list[dict]]:
    """Concatenate each arm's own alternatives, contact first, deterministically."""
    from cv.pipeline import s6_optional_contacts

    conditional = conditional_policy(conditional_grounds) == "on"
    held = documents["bounce"].get("null_hold")
    alternatives: list[dict] = []
    receipts: list[dict] = []
    by_family: dict[str, list[dict]] = {family: [] for family in FAMILIES}
    for family in FAMILIES:
        # A held no-addition scope means the accepted ground tail never qualified.
        # The contact mechanism only proposes interior contacts between two
        # accepted contacts, so it cannot change that tail and its topologies were
        # never qualified for this attempt's scope container. Abstain explicitly
        # rather than let an unqualified winner reach the scope reader.
        if family == "contact" and held is not None and not final_contact_scope(documents):
            receipts.append(
                {
                    "source_family": family,
                    "status": "not_eligible",
                    "alternatives": 0,
                    "reason": f"unqualified no-addition observation scope: {held}",
                }
            )
            continue
        rows = [
            {**row, "source_family": family}
            for row in s6_optional_contacts.search_hypotheses(documents[family], attempt)
        ]
        receipts.append({"source_family": family, "status": "eligible", "alternatives": len(rows)})
        by_family[family] = rows
        alternatives.extend(rows)
    if composes(documents):
        blocked = next(
            (
                f"{family} arm contributed no alternative"
                for family in FAMILIES
                if not by_family[family]
            ),
            None,
        )
        if blocked is not None:
            receipts.append(
                {
                    "source_family": JOINT,
                    "status": "not_eligible",
                    "alternatives": 0,
                    "reason": blocked,
                }
            )
        else:
            joint, pairs = composed(documents, attempt, by_family)
            receipts.append(
                {
                    "source_family": JOINT,
                    "status": "eligible",
                    "alternatives": len(joint),
                    "pair_order": pair_order(by_family),
                    "source_ordered_pairs": pairs,
                }
            )
            alternatives.extend(joint)
    if conditional:
        # A second bounded family under the explicit policy. It needs only the
        # contact arm: its grounds are qualified under each contact hypothesis,
        # not taken from the bounce arm's own beam, which stays as offered above.
        if not by_family["contact"]:
            receipts.append(
                {
                    "source_family": JOINT,
                    "composition": CONDITIONAL,
                    "status": "not_eligible",
                    "alternatives": 0,
                    "reason": "contact arm contributed no alternative",
                }
            )
        else:
            existing = [row for row in alternatives if row["source_family"] == JOINT]
            # Only the original-pair branches count against the shared cap; the
            # timing subfamily already has its own separate limit above.
            timing = {
                r["name"] for r in by_family["contact"] if r.get("contact_timing_alternative")
            }
            original_composed = [
                row
                for row in existing
                if row["joint_composition"]["contact_hypothesis"] not in timing
            ]
            allowed = max(0, MAX_JOINT - len(original_composed))
            joint, pairs = conditional_pairs(documents, attempt, by_family, existing, allowed)
            receipts.append(
                {
                    "source_family": JOINT,
                    "composition": CONDITIONAL,
                    "status": "eligible",
                    "alternatives": len(joint),
                    "existing_original_joint_alternatives": len(original_composed),
                    "shared_joint_pair_limit": MAX_JOINT,
                    "conditional_pairs_allowed": allowed,
                    "pair_order": "contact_arm_order_then_conditional_beam_v1",
                    "source_ordered_pairs": pairs,
                }
            )
            alternatives.extend(joint)
    names = [row["name"] for row in alternatives]
    if len(set(names)) != len(names):
        raise ValueError("joint optional beams produced a duplicate topology name")
    return alternatives, receipts


def selection_fields(
    winner_name: str,
    hypothesis: dict,
    receipts: list[dict],
    bindings: dict,
    witnesses: dict[str, dict],
) -> dict:
    """Joint selection fields naming the winning family and its own witness.

    The no-addition branch belongs to neither beam. The bounce witness records
    whether its scope is eligible, so it carries that family's policy and record
    while the selection still declares ``supplied`` as the family that won.
    """
    family = family_of(winner_name)
    if family is None:
        raise ValueError("joint optional winner must name a source family topology")
    added = len(hypothesis.get("added", []))
    if family == JOINT:
        # A composed winner belongs to no single witness, so it carries its own
        # policy and both witness records rather than borrowing an arm's.
        if not bindings.get("cross_composed_events"):
            raise ValueError("composed optional winner requires the v2 composing source bindings")
        contacts = hypothesis["added_contact_count"]
        bounces = hypothesis["added_bounce_count"]
        if contacts + bounces != added or hypothesis["added_parameter_count"] != 6 * contacts:
            raise ValueError("composed optional winner dimensions differ from its own arms")
        return {
            "policy": POLICIES[JOINT],
            "witness_records": {family: witnesses[family] for family in FAMILIES},
            "joint_source_families": list(FAMILIES),
            "source_family": JOINT,
            "joint_composition": hypothesis["joint_composition"],
            "optional_family_receipts": receipts,
            "source_bindings": bindings,
            "added_contact_count": contacts,
            "added_bounce_count": bounces,
            "added_parameter_count": hypothesis["added_parameter_count"],
            "legacy_selection_field": "optional_contact_selection",
        }
    owner = "contact" if family == "contact" else "bounce"
    return {
        "policy": POLICIES[owner],
        "witness_record": witnesses[owner],
        "joint_source_families": list(FAMILIES),
        "source_family": family,
        **(
            {"scope": bindings["final_contact_scope"]}
            if family == "contact" and bindings.get("final_contact_scope") is not None
            else {}
        ),
        "optional_family_receipts": receipts,
        "source_bindings": bindings,
        "added_contact_count": added if family == "contact" else 0,
        "added_bounce_count": added if family == "bounce" else 0,
        "added_parameter_count": 0
        if family == SUPPLIED
        else hypothesis.get("added_parameter_count"),
        "legacy_selection_field": "optional_contact_selection",
    }


def joint_documents(attempt: dict, selection: dict) -> dict[str, dict]:
    """Reload both declared source witnesses for a composed selection.

    The bounce witness is rebuilt from its own source by its ordinary loader; the
    contact witness is resolved by its declared record exactly as the contact
    reader does. No document is concatenated and no third witness exists.
    """
    import json

    from cv.pipeline import s6_optional_bounce_scope
    from cv.pipeline.s6_labeled_stage import resolve

    records = selection.get("witness_records")
    if not isinstance(records, dict) or set(records) != set(FAMILIES):
        raise ValueError("composed optional selection requires both source witness records")
    if selection.get("witness_record") is not None:
        raise ValueError("composed optional selection cannot name one owning witness")
    if records["bounce"] != attempt.get("optional_bounce_witness"):
        raise ValueError("composed optional bounce witness differs from packet")
    record = records["contact"]
    if not isinstance(record, dict) or not isinstance(record.get("sha256"), str):
        raise ValueError("composed optional contact witness needs a declared source binding")
    path = resolve(record)
    if provenance.file_sha256(path) != record["sha256"]:
        raise ValueError("composed optional contact witness changed before replay")
    return {
        "contact": json.loads(path.read_text()),
        "bounce": s6_optional_bounce_scope.load_witness(attempt),
    }


def _validate_joint_report(attempt: dict, report: dict, selection: dict) -> bool:
    documents = joint_documents(attempt, selection)
    # The recorded composition policy is replayed here; the export reader also
    # checks it against the shared policy, so a flipped flag cannot admit a winner.
    conditional = conditional_policy(selection.get("optional_conditional_grounds"))
    if not composes(documents) and conditional != "on":
        raise ValueError(
            "composed optional selection requires the final-contact source scope"
            if final_contact_scope(documents)
            else "composed optional selection requires the v2 bounce source witness"
        )
    if selection.get("source_bindings") != check_source_binding(documents, attempt, conditional):
        raise ValueError("composed optional source bindings differ from the original witnesses")
    alternatives, receipts = hypotheses(documents, attempt, conditional)
    if selection.get("optional_family_receipts") != receipts:
        raise ValueError("composed optional family eligibility differs from the source witnesses")
    if not any(
        row["source_family"] == JOINT
        and row["name"] == selection.get("selected_topology")
        and row["events"] == report.get("events")
        and row["joint_composition"] == selection.get("joint_composition")
        and row["added_contact_count"] == selection.get("added_contact_count")
        and row["added_bounce_count"] == selection.get("added_bounce_count")
        and row["added_parameter_count"] == selection.get("added_parameter_count")
        for row in alternatives
    ):
        raise ValueError("selected events are not a recomputed composed source hypothesis")
    return True


def selection_family(selection: dict) -> str | None:
    return next((f for f, policy in POLICIES.items() if selection.get("policy") == policy), None)


def validate_report_events(attempt: dict, report: dict) -> bool:
    """Route a report to the single-arm reader that owns its declared family.

    Each reader still decides eligibility from its own source witness; this only
    refuses a selection whose declared family, winning topology name and packet
    witnesses disagree, so no arm can validate the other's winner by default.
    """
    from cv.pipeline import s6_optional_bounce_scope, s6_optional_contacts

    selection = report.get("optional_contact_selection")
    if not selection:
        return False
    from cv.pipeline import s6_terminal_net_membership as net_membership

    if selection.get("policy") == net_membership.SELECTION_POLICY:
        # A declared terminal-net membership with no ordinary optional witness.
        # Its own shared resolver owns the branch; no witness family applies.
        return False
    policy_family = selection_family(selection)
    if policy_family is None:
        raise ValueError("optional selection must declare a supported source witness family")
    winner = family_of(selection.get("selected_topology"))
    if winner is None or (winner != SUPPLIED and winner != policy_family):
        raise ValueError("optional selected topology does not belong to its declared family")
    if (policy_family == JOINT) != (winner == JOINT):
        raise ValueError("composed optional winner and policy must name the same family")
    from cv.pipeline import s6_contact_prefix_scope as prefix

    contract = attempt.get("observation_scope") or {}
    if contract.get("schema") == prefix.SCHEMA:
        # Prefix preparation preserves original witness records as ancestry,
        # while its applied policy disables bounce/joint families. Presence of
        # an archival bounce witness does not make that family active here.
        if (
            contract.get("mode") != prefix.TERMINAL_IDENTITY
            or policy_family != "contact"
            or selection.get("joint_source_families") is not None
        ):
            raise ValueError("contact prefix replay requires a contact-only interior witness")
        # Recompute source-local eligibility and exact winning events through
        # the existing reader; no other prefix topology gains admission.
        return s6_optional_contacts.validate_report_events(attempt, report)
    joint = selection.get("joint_source_families")
    if policy_family == JOINT:
        if sorted(joint or ()) != sorted(FAMILIES) or selection.get("source_family") != JOINT:
            raise ValueError("composed optional selection must declare both source witnesses")
        return _validate_joint_report(attempt, report, selection)
    if joint is None:
        if attempt.get("optional_bounce_witness") and policy_family != "bounce":
            raise ValueError("single-arm bounce report cannot select another witness family")
    else:
        if sorted(joint) != sorted(FAMILIES) or not attempt.get("optional_bounce_witness"):
            raise ValueError("unsupported joint optional source families")
        if selection.get("source_family") != (winner if winner == SUPPLIED else policy_family):
            raise ValueError("joint optional selection family differs from its winning topology")
        if (
            winner == "contact"
            and s6_optional_bounce_scope.load_witness(attempt).get("null_hold") is not None
        ):
            raise ValueError("contact winner cannot qualify a held optional bounce scope")
    if policy_family == "bounce":
        return s6_optional_bounce_scope.validate_report_events(attempt, report)
    return s6_optional_contacts.validate_report_events(attempt, report)
